---
title: Mohammad Zain Abbas
timezone: Europe/Paris
collections:
  posts:
    title: Posts
    output: true
  tabs:
    title: Tabs
    output: true
    sort_by: order
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    comments: true
    toc: true
    permalink: "/posts/:title/"
- scope:
    path: _drafts
  values:
    comments: false
- scope:
    path: ''
    type: tabs
  values:
    layout: page
    permalink: "/:title/"
- scope:
    path: assets/img/favicons
  values:
    swcache: true
- scope:
    path: assets/js/dist
  values:
    swcache: true
theme: jekyll-theme-chirpy
lang: en
tagline: 'Journey through knowledge: From silicon to the stars'
description: 'Welcome to ''Journey through knowledge: From silicon to the stars''
  - a unique blend of tech insights, astronomical wonders, and travel tales. Dive
  into a world where cutting-edge technology meets the mysteries of the cosmos. Follow
  along as we decode the latest in tech, gaze into the starlit skies, and embark on
  journeys to breathtaking destinations. This is your gateway to exploring the intersections
  of technology, astronomy, and travel, sharing learnings and experiences that inspire
  and inform. Whether you''re a tech enthusiast, a starry-eyed astronomer, or a wanderlust-driven
  traveler, there''s something here for everyone. Join the journey and expand your
  horizons with every post!'
url: https://mohammadzainabbas.github.io
github:
  username: mohammadzainabbas
twitter:
  username: star_on_earth
social:
  name: Mohammad Zain Abbas
  email: mohammadzainabbas@gmail.com
  links:
  - https://twitter.com/star_on_earth
  - https://github.com/mohammadzainabbas
  - https://www.linkedin.com/in/mohammadzainabbas
google_site_verification: YIx1XHjp1YHIT5zYJO3UByDcJiozlE1IjSg7sxJ6Cn8
google_analytics:
  id: 
theme_mode: 
img_cdn: 
avatar: https://avatars.githubusercontent.com/u/19189095
toc: true
comments:
  active: 
  disqus:
    shortname: 
  utterances:
    repo: 
    issue_term: 
  giscus:
    repo: 
    repo_id: 
    category: 
    category_id: 
    mapping: 
    input_position: 
    lang: 
    reactions_enabled: 
assets:
  self_host:
    enabled: 
    env: 
pwa:
  enabled: true
paginate: 10
baseurl: ''
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
sass:
  style: compressed
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs:
    - development
exclude:
- "*.gem"
- "*.gemspec"
- docs
- tools
- README.md
- LICENSE
- rollup.config.js
- package*.json
jekyll-archives:
  enabled:
  - categories
  - tags
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: "/tags/:name/"
    category: "/categories/:name/"
